{% set version = "0.5.2" %}

package:
  name: pywavelets
  version: {{ version }}

source:
  url: https://github.com/PyWavelets/pywt/archive/v{{ version }}.tar.gz
  sha256: e36d629f40f7781da2dcaa2139bc476e9deaf91d79f675b5ce0bde6e775d1b53

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - cython
    - setuptools
    - numpy 1.8.*  # [not (win and py36)]
    - numpy 1.11.*  # [win and py36]
  run:
    - python
    - numpy >=1.8  # [not (win and py36)]
    - numpy >=1.11  # [win and py36]

test:
  requires:
    - nose
  commands:
    - conda inspect linkages -p $PREFIX pywavelets  # [not win]
    - conda inspect objects -p $PREFIX pywavelets   # [osx]

about:
  home: https://github.com/PyWavelets/pywt
  license: MIT
  license_file: COPYING
  summary: 'Discrete Wavelet Transforms in Python.'

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - ocefpaf
