travis:
  secure:
    BINSTAR_TOKEN: CBo97qRmhh5R2W2l0U7F3F1F+CkRz3WWgEGhEUs4sLe+/9orVa+2aItGj8H55bUaxPnNONUD5Pjtf5qQ/YubXjmEQY9+0z3SRXeGAksvXrWlPih2seiEInfHZo11VcN/yWx6vFIATiIy3EMtkHJGGMzNJwJBNKNkFOirh4ZBq5M9W6Jk3ef7xcV6WhD4Yh+mUuirVXepn+rCsChkbGWAntpN6R4kNdFxIq4H+OgnKcx+Fl9U4uBWdTSlPlErDEbn8oOuh6R60tOHwFkajm/G4RdtzJsuP40pE4bcwmn7F38jsiqfZ6r33iZ2g0adO8c16PO8uuix3Waks36juY2Sb7pL4mMm5PNaxL6dT94tqGaegfPf1sV7BUdvRkUG8qrFGp45OSrCEIu85DdCUqbBGp76zK72rVbnK58Ym8AM8aRFYgQuQzTfW74CGYSttm4Imi60S/wgrzvzoBR/9q3GOQRtOTfhtJsnBY+ZlYc/ac0FFVJf9S9NlOoLoms84eRgTS4w0cljClynYqY+ttBCHIXEsC9xiancTw2q1+CHSgXIaEqp101yOAXR6ilom7B0kpJZT70O1MC3O8y8zpe8Y5PDhMRM7Wz8ubCaZGgZ8cv2/36h9NejH92SlmV/6Pp5wTHXTnIm0OoBbNuq2QklzCCnKj9Hf86yi+USv/lIKhM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
channels:
  sources:
    - conda-forge/label/broken
    - conda-forge
    - defaults
